# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plr < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    url "https://github.com/dpastoor/plr/releases/download/v0.0.1/plr_Darwin_all.tar.gz"
    sha256 "2479193eefea72cbd7036bd43b7afea074e3b7feb3e39f74e4f6b8b523c3cb91"

    def install
      bin.install "plr"
      bash_completion.install "completions/plr.bash" => "plr"
      zsh_completion.install "completions/plr.zsh" => "_plr"
      fish_completion.install "completions/plr.fish"
      man1.install "manpages/plr.1.gz"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dpastoor/plr/releases/download/v0.0.1/plr_Linux_x86_64.tar.gz"
      sha256 "f9c629548adfddd7141880381223d34f685e42524a54c117038440ed9957dc76"

      def install
        bin.install "plr"
        bash_completion.install "completions/plr.bash" => "plr"
        zsh_completion.install "completions/plr.zsh" => "_plr"
        fish_completion.install "completions/plr.fish"
        man1.install "manpages/plr.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpastoor/plr/releases/download/v0.0.1/plr_Linux_arm64.tar.gz"
      sha256 "2b77b94db063f909efe8dd67ef15c01bc1be59c60b5d6f2524ecfcfeeea81ba2"

      def install
        bin.install "plr"
        bash_completion.install "completions/plr.bash" => "plr"
        zsh_completion.install "completions/plr.zsh" => "_plr"
        fish_completion.install "completions/plr.fish"
        man1.install "manpages/plr.1.gz"
      end
    end
  end

  test do
    system "#{bin}/plr -v"
  end
end
