# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qvm < Formula
  desc ""
  homepage ""
  version "0.0.7"

  on_macos do
    url "https://github.com/dpastoor/qvm/releases/download/v0.0.7/qvm_Darwin_all.tar.gz"
    sha256 "a5ae880e9a85413662982be602f64ba28431b2ec930ed4231863418dde65a0b5"

    def install
      bin.install "qvm"
      bash_completion.install "completions/qvm.bash" => "qvm"
      zsh_completion.install "completions/qvm.zsh" => "_qvm"
      fish_completion.install "completions/qvm.fish"
      man1.install "manpages/qvm.1.gz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpastoor/qvm/releases/download/v0.0.7/qvm_Linux_arm64.tar.gz"
      sha256 "6cae1579513479c6f838f217f77b2a6d89585b32c369fc3c019a6d12be7ae649"

      def install
        bin.install "qvm"
        bash_completion.install "completions/qvm.bash" => "qvm"
        zsh_completion.install "completions/qvm.zsh" => "_qvm"
        fish_completion.install "completions/qvm.fish"
        man1.install "manpages/qvm.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpastoor/qvm/releases/download/v0.0.7/qvm_Linux_x86_64.tar.gz"
      sha256 "d9c8d8fa7381a84faa53b1969d7f9414c4f16e7b02547bd9aba0b066f0b98d6e"

      def install
        bin.install "qvm"
        bash_completion.install "completions/qvm.bash" => "qvm"
        zsh_completion.install "completions/qvm.zsh" => "_qvm"
        fish_completion.install "completions/qvm.fish"
        man1.install "manpages/qvm.1.gz"
      end
    end
  end

  test do
    system "#{bin}/qvm -v"
  end
end
