# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qvm < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    url "https://github.com/dpastoor/qvm/releases/download/v0.0.2/qvm_Darwin_x86_64.tar.gz"
    sha256 "9547a60ca97a2040738c464ed43b6f0c0b6d1e0e06ba76d21368f94f55d6425a"

    def install
      bin.install "qvm"
      bash_completion.install "completions/qvm.bash" => "qvm"
      zsh_completion.install "completions/qvm.zsh" => "_qvm"
      fish_completion.install "completions/qvm.fish"
      man1.install "manpages/qvm.1.gz"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Qvm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dpastoor/qvm/releases/download/v0.0.2/qvm_Linux_x86_64.tar.gz"
      sha256 "f045377d0a4929508284788da726ec29d03cd90fe4de30f6c445acbd7babd505"

      def install
        bin.install "qvm"
        bash_completion.install "completions/qvm.bash" => "qvm"
        zsh_completion.install "completions/qvm.zsh" => "_qvm"
        fish_completion.install "completions/qvm.fish"
        man1.install "manpages/qvm.1.gz"
      end
    end
  end

  test do
    system "#{bin}/qvm -v"
  end
end
